# Site settings
title: Kyle Stewart
email: me@kylestewart.co
description: > # this means to ignore newlines until "baseurl:"
  Kyle Stewart | Technical Creative
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kylestewart.co" # the base hostname & protocol for your site
twitter_username: kyleRstewart
github_username:  kylestew

# Build settings
markdown: kramdown
