# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Stewart
email: me@kylestewart.co
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Kyle Stewart
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kylestewart.co" # the base hostname & protocol for your site
twitter_username: kyleRstewart
github_username:  kylestew

exclude: [ comps ]

# Build settings
markdown: kramdown

gems:
  - jekyll-assets
  - breakpoint
